
services:
  postgres:
    container_name: farming_districts_postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: var/lib/data/postgresql