server:
  port: 9000

spring:
  application:
    name: farming-district-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

springdoc:
  api-docs:
    enabled: true
    path: /farming-district/v3/api-docs